services:
  db-config:
    image: postgres:15
    restart: unless-stopped
    networks:
      - banking
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'" ]
      interval: 30s
      timeout: 10s
      retries: 5