spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB:test}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KC_JWKS_URI}

eureka:
  client:
    enabled: false

info:
  app:
    name: ${SPRING_APPLICATION_NAME}
    description: "Microservices-based Mini-Banking backend system - ${spring.application.name} service"