spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KC_JWKS_URI}

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka

info:
  app:
    name: ${SPRING_APPLICATION_NAME}
    description: "Microservices-based Mini-Banking backend system - ${spring.application.name} service"