spring:
  cloud:
    openfeign:
      okhttp:
        enabled: true
      oauth2:
        enabled: true
        clientRegistrationId: keycloak
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: ${KC_CLIENT_ID}
            client-secret: ${KC_CLIENT_SECRET}
            scope: openid
        provider:
          keycloak:
            token-uri: ${KC_ACCESS_TOKEN}
      resourceserver:
        jwt:
          jwk-set-uri: ${KC_JWKS_URI}

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka

info:
  app:
    name: ${SPRING_APPLICATION_NAME}
    description: "Microservices-based Mini-Banking backend system - ${spring.application.name} service"